### ISSUE TITLE
Is the website down?

### ISSUE THREAD

**Issue by dr-dimitru** [bacloud23/mylinks#34]
I wanted to check out the project's website, but it isn't available
![Screen Shot 2022-05-30 at 11 29 53 AM](https://user-images.githubusercontent.com/1686778/170951333-a8a05cab-0fc3-4e30-8267-41087e32a87c.png)

**Comment by bacloud22** [comment]
yep, I discontinued hosting for all apps until I start a job (lol)
However, you could just try it, it's just browser JS (maybe you need to change some host name in code, or  everything is self contained -- I don't remember).

**Comment by bacloud23** [comment]
mylinks.space
