### ISSUE TITLE
Better design 

### ISSUE THREAD

**Issue by bacloud23** [bacloud23/mylinks#61]
I've got some feedbacks about the choice of colours. So I really don't know what would be better.

**Comment by serzhan181** [comment]
I am not a very good designer myself, but i still dont think putting dark colored icons on the dark background is a good idea.
![изображение](https://user-images.githubusercontent.com/67381256/217171288-8347a0c2-2ada-4c58-bd25-f64256ad9010.png)

**Comment by bacloud23** [comment]
thanks for the feedback I will work on that

**Comment by bacloud23** [comment]
fixed
